lib/quizzical_web/router.ex
defmodule QuizzicalWeb.Router do
  use QuizzicalWeb, :router

  import QuizzicalWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {QuizzicalWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", QuizzicalWeb do
    pipe_through :browser

    get "/attribution", PageController, :attribution
    get "/privacy", PageController, :privacy

    live "/", QuestionLive.Index, :index
    live "/questions/:id/edit", QuestionLive.Index, :edit
    live "/questions/new", QuestionLive.Index, :new
    live "/questions/:id", QuestionLive.Show, :show

    live "/categories", CategoryLive.Index, :index
    live "/categories/new", CategoryLive.Index, :new
    live "/categories/:slug/edit", CategoryLive.Index, :edit

    live "/categories/:slug", CategoryLive.Show, :show
    live "/categories/:slug/show/edit", CategoryLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", QuizzicalWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: QuizzicalWeb.Telemetry
    end
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  ## Authentication routes

  scope "/", QuizzicalWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", QuizzicalWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", QuizzicalWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/quizzical_web/controllers/user_registration_controller.ex
defmodule QuizzicalWeb.UserRegistrationController do
  use QuizzicalWeb, :controller

  alias Quizzical.Accounts
  alias Quizzical.Accounts.User
  alias QuizzicalWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :confirm, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/quizzical_web/views/user_registration_view.ex
defmodule QuizzicalWeb.UserRegistrationView do
  use QuizzicalWeb, :view
end

lib/quizzical_web/templates/user_registration/new.html.eex
<div class="auth-container">
  <div class="max-w-md w-full space-y-8">
    <div>
      <h2>Sign up to Quizzical</h2>
    </div>
    <%= form_for @changeset, Routes.user_registration_path(@conn, :create), [class: "auth"], fn f -> %>
      <input type="hidden" name="remember" value="true">
      <div class="-space-y-px">
        <div>
          <%= label f, :email, class: 'sr-only' %>
          <%= email_input f, :email, required: true, class: "rounded-t-md", placeholder: "Email address" %>
          <%= error_tag f, :email %>
        </div>
        <div>
          <%= label f, :password, class: 'sr-only' %>
          <%= password_input f, :password, required: true, class: "rounded-b-md", placeholder: "Password" %>
          <%= error_tag f, :password %>
        </div>
      </div>

      <div class="flex items-center justify-between">
        <div class="text-sm">
          <%= link "Log in", to: Routes.user_session_path(@conn, :new), class: "font-medium text-indigo-600 hover:text-indigo-500" %>
        </div>

        <div class="text-sm">
          <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "font-medium text-indigo-600 hover:text-indigo-500" %>
        </div>
      </div>


      <div>
        <%= submit do %>
          <span class="absolute left-0 inset-y-0 flex items-center pl-3">
            <!-- Heroicon name: solid/lock-closed -->
            <svg class="h-5 w-5 text-indigo-500 group-hover:text-indigo-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
            </svg>
          </span>
          Sign up
        <% end %>
      </div>
    <% end %>
  </div>
</div>

lib/quizzical_web/templates/user_registration/new.html.heex
<div class="auth-container">
  <div class="max-w-md w-full space-y-8">
    <div>
      <h2>Sign up to Quizzical</h2>
    </div>
    <%= form_for @changeset, Routes.user_registration_path(@conn, :create), [class: "auth"], fn f -> %>
      <input type="hidden" name="remember" value="true">
      <div class="-space-y-px">
        <div>
          <%= label f, :email, class: "sr-only" %>
          <%= email_input f, :email, required: true, class: "rounded-t-md", placeholder: "Email address" %>
          <%= error_tag f, :email %>
        </div>
        <div>
          <%= label f, :password, class: "sr-only" %>
          <%= password_input f, :password, required: true, class: "rounded-b-md", placeholder: "Password" %>
          <%= error_tag f, :password %>
        </div>
      </div>

      <div class="flex items-center justify-between">
        <div class="text-sm">
          <%= link "Log in", to: Routes.user_session_path(@conn, :new), class: "font-medium text-indigo-600 hover:text-indigo-500" %>
        </div>

        <div class="text-sm">
          <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "font-medium text-indigo-600 hover:text-indigo-500" %>
        </div>
      </div>


      <div>
        <%= submit do %>
          <span class="absolute left-0 inset-y-0 flex items-center pl-3">
            <!-- Heroicon name: solid/lock-closed -->
            <svg class="h-5 w-5 text-indigo-500 group-hover:text-indigo-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
            </svg>
          </span>
          Sign up
        <% end %>
      </div>
    <% end %>
  </div>
</div>