lib/quizzical_web/router.ex
defmodule QuizzicalWeb.Router do
  use QuizzicalWeb, :router

  import QuizzicalWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {QuizzicalWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", QuizzicalWeb do
    pipe_through :browser

    get "/attribution", PageController, :attribution
    get "/privacy", PageController, :privacy

    live "/", QuestionLive.Index, :index
    live "/questions/:id/edit", QuestionLive.Index, :edit
    live "/questions/new", QuestionLive.Index, :new
    live "/questions/:id", QuestionLive.Show, :show

    live "/categories", CategoryLive.Index, :index
    live "/categories/new", CategoryLive.Index, :new
    live "/categories/:slug/edit", CategoryLive.Index, :edit

    live "/categories/:slug", CategoryLive.Show, :show
    live "/categories/:slug/show/edit", CategoryLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", QuizzicalWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: QuizzicalWeb.Telemetry
    end
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  ## Authentication routes

  scope "/", QuizzicalWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", QuizzicalWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", QuizzicalWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/quizzical_web/views/shared_view.ex
defmodule QuizzicalWeb.SharedView do
  use QuizzicalWeb, :view
end

lib/quizzical_web/templates/shared/nav.html.eex
<nav class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button
          id="nav-menu"
          class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
          aria-expanded="false"
        >
          <span class="sr-only">Open main menu</span>
          <!-- Icon when menu is closed. -->
          <!--
            Heroicon name: outline/menu

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg
            class="block h-6 w-6"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            aria-hidden="true"
          >
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <!-- Icon when menu is open. -->
          <!--
            Heroicon name: outline/x

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg
            class="hidden h-6 w-6"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            aria-hidden="true"
          >
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>

        <script type="text/javascript">
          document.getElementById("nav-menu").onclick = function () {
            var el = document.querySelector(".mobile-nav");

            el.classList.toggle("hidden");
          };
        </script>
      </div>

      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
        <a class="flex-shrink-0 flex items-center text-indigo-600" href="/">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="icon icon-tabler icon-tabler-zoom-question"
            width="36"
            height="36"
            viewBox="0 0 24 24"
            stroke-width="2"
            stroke="currentColor"
            fill="none"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <circle cx="10" cy="10" r="7"></circle>
            <path d="M21 21l-6 -6"></path>
            <line x1="10" y1="13" x2="10" y2="13.01"></line>
            <path d="M10 10a1.5 1.5 0 1 0 -1.14 -2.474"></path>
          </svg>
          <h1 class="text-xl text-white font-sans tracking-tighter subpixel-antialiased font-bold uppercase">
            Pub Quiz Builder
          </h1>
        </a>
        <div class="hidden sm:block sm:ml-6">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->

            <%= link "Home", to: Routes.question_index_path(@conn, :index), class: "bg-gray-900 nav-link" %>
            <%= link "Categories", to: Routes.category_index_path(@conn, :index), class: "nav-link" %>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <!-- Profile dropdown -->
        <div class="ml-3 relative">
          <div>
            <button
              class="bg-gray-800 flex text-sm rounded-full outline-none ring-2 ring-offset-2 ring-offset-gray-800 ring-white"
              id="user-menu"
              aria-haspopup="true"
            >
              <span class="sr-only">Open user menu</span>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="icon icon-tabler icon-tabler-user"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                stroke-width="2"
                stroke="white"
                fill="none"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <circle cx="12" cy="7" r="4"></circle>
                <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path>
              </svg>
            </button>

            <script type="text/javascript">
              document.getElementById("user-menu").onclick = function () {
                var el = document.querySelector(".account-dd");

                el.classList.toggle("opacity-0");
                el.classList.toggle("opacity-100");
              };
            </script>
          </div>
          <!--
            Profile dropdown panel, show/hide based on dropdown state.

            Entering: "transition ease-out duration-100"
              From: "transform opacity-0 scale-95"
              To: "transform opacity-100 scale-100"
            Leaving: "transition ease-in duration-75"
              From: "transform opacity-100 scale-100"
              To: "transform opacity-0 scale-95"
          -->
          <div class="account-dd opacity-0" role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
            <%= if @current_user do %>
              <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), role: "menuitem" %>
              <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete, role: "menuitem" %>
            <% else %>
              <%= link "Register", to: Routes.user_registration_path(@conn, :new), role: "menuitem" %>
              <%= link "Log in", to: Routes.user_session_path(@conn, :new), role: "menuitem" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!--
    Mobile menu, toggle classes based on menu state.

    Menu open: "block", Menu closed: "hidden"
  -->
  <div class="hidden sm:hidden mobile-nav">
    <div class="px-2 pt-2 pb-3 space-y-1">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->

      <%= link "Home", to: Routes.question_index_path(@conn, :index), class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
      <%= link "Categories", to: Routes.category_index_path(@conn, :index), class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
    </div>
  </div>
</nav>

lib/quizzical_web/templates/shared/nav.html.heex
<nav class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button
          id="nav-menu"
          class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
          aria-expanded="false"
        >
          <span class="sr-only">Open main menu</span>
          <!-- Icon when menu is closed. -->
          <!--
            Heroicon name: outline/menu

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg
            class="block h-6 w-6"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            aria-hidden="true"
          >
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <!-- Icon when menu is open. -->
          <!--
            Heroicon name: outline/x

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg
            class="hidden h-6 w-6"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            aria-hidden="true"
          >
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>

        <script type="text/javascript">
          document.getElementById("nav-menu").onclick = function () {
            var el = document.querySelector(".mobile-nav");

            el.classList.toggle("hidden");
          };
        </script>
      </div>

      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
        <a class="flex-shrink-0 flex items-center text-indigo-600" href="/">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="icon icon-tabler icon-tabler-zoom-question"
            width="36"
            height="36"
            viewBox="0 0 24 24"
            stroke-width="2"
            stroke="currentColor"
            fill="none"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <circle cx="10" cy="10" r="7"></circle>
            <path d="M21 21l-6 -6"></path>
            <line x1="10" y1="13" x2="10" y2="13.01"></line>
            <path d="M10 10a1.5 1.5 0 1 0 -1.14 -2.474"></path>
          </svg>
          <h1 class="text-xl text-white font-sans tracking-tighter subpixel-antialiased font-bold uppercase">
            Pub Quiz Builder
          </h1>
        </a>
        <div class="hidden sm:block sm:ml-6">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->

            <%= link "Home", to: Routes.question_index_path(@conn, :index), class: "bg-gray-900 nav-link" %>
            <%= link "Categories", to: Routes.category_index_path(@conn, :index), class: "nav-link" %>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <!-- Profile dropdown -->
        <div class="ml-3 relative">
          <div>
            <button
              class="bg-gray-800 flex text-sm rounded-full outline-none ring-2 ring-offset-2 ring-offset-gray-800 ring-white"
              id="user-menu"
              aria-haspopup="true"
            >
              <span class="sr-only">Open user menu</span>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="icon icon-tabler icon-tabler-user"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                stroke-width="2"
                stroke="white"
                fill="none"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <circle cx="12" cy="7" r="4"></circle>
                <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path>
              </svg>
            </button>

            <script type="text/javascript">
              document.getElementById("user-menu").onclick = function () {
                var el = document.querySelector(".account-dd");

                el.classList.toggle("opacity-0");
                el.classList.toggle("opacity-100");
              };
            </script>
          </div>
          <!--
            Profile dropdown panel, show/hide based on dropdown state.

            Entering: "transition ease-out duration-100"
              From: "transform opacity-0 scale-95"
              To: "transform opacity-100 scale-100"
            Leaving: "transition ease-in duration-75"
              From: "transform opacity-100 scale-100"
              To: "transform opacity-0 scale-95"
          -->
          <div class="account-dd opacity-0" role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
            <%= if @current_user do %>
              <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), role: "menuitem" %>
              <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete, role: "menuitem" %>
            <% else %>
              <%= link "Register", to: Routes.user_registration_path(@conn, :new), role: "menuitem" %>
              <%= link "Log in", to: Routes.user_session_path(@conn, :new), role: "menuitem" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!--
    Mobile menu, toggle classes based on menu state.

    Menu open: "block", Menu closed: "hidden"
  -->
  <div class="hidden sm:hidden mobile-nav">
    <div class="px-2 pt-2 pb-3 space-y-1">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->

      <%= link "Home", to: Routes.question_index_path(@conn, :index), class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
      <%= link "Categories", to: Routes.category_index_path(@conn, :index), class: "text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" %>
    </div>
  </div>
</nav>

lib/quizzical_web/templates/shared/question_list.html.heex
<div class="sm:shadow sm:border-b sm:border-gray-200 sm:rounded-lg">
  <table class="divide-y divide-gray-200">
    <tbody class="">
      <%= for question <- @question_page.results do %>
        <tr
          class="flex flex-col sm:table-row mb-6 sm:mb-0 rounded-lg sm:rounded-none border sm:border-0 sm:border-b"
          id={"question-#{question.id}"}
        >
          <td class="px-6 py-4 break-all sm:break-normal">
            <strong><%= question.question %>?</strong>
          </td>
          <td class="px-6 sm:py-4 py-2">
            <%= question.answer %>
          </td>
          <td class="px-6 py-4 whitespace-nowrap">
            <%= for category <- question.categories do %>
              <span
                class="rounded bg-indigo-600 py-1 px-2 text-sm text-white hover:bg-indigo-800"
              ><%= live_patch category.name, to: Routes.category_show_path(@socket, :show, category) %></span>
            <% end %>
          </td>
          <%= if @current_user && @current_user.is_admin do %>
            <td class="action-cell hidden sm:block">
              <%= live_patch "Edit", to: Routes.question_index_path(@socket, :edit, question) %>
            </td>
          <% end %>

          <%= if @current_user && @current_user.is_admin do %>
            <td class="action-cell hidden sm:block">
              <%= link "Delete", to: "#", phx_click: "delete", phx_value_id: question.id, data: [confirm: "Are you sure?"] %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

lib/quizzical_web/templates/shared/question_list.html.leex
<div class="sm:shadow sm:border-b sm:border-gray-200 sm:rounded-lg">
  <table class="divide-y divide-gray-200">
    <tbody class="">
      <%= for question <- @question_page.results do %>
        <tr
          class="flex flex-col sm:table-row mb-6 sm:mb-0 rounded-lg sm:rounded-none border sm:border-0 sm:border-b"
          id="question-<%= question.id %>"
        >
          <td class="px-6 py-4 break-all sm:break-normal">
            <strong><%= question.question %>?</strong>
          </td>
          <td class="px-6 sm:py-4 py-2">
            <%= question.answer %>
          </td>
          <td class="px-6 py-4 whitespace-nowrap">
            <%= for category <- question.categories do %>
              <span
                class="rounded bg-indigo-600 py-1 px-2 text-sm text-white hover:bg-indigo-800"
              ><%= live_patch category.name, to: Routes.category_show_path(@socket, :show, category) %></span>
            <% end %>
          </td>
          <%= if @current_user && @current_user.is_admin do %>
            <td class="action-cell hidden sm:block">
              <%= live_patch "Edit", to: Routes.question_index_path(@socket, :edit, question) %>
            </td>
          <% end %>

          <%= if @current_user && @current_user.is_admin do %>
            <td class="action-cell hidden sm:block">
              <%= link "Delete", to: "#", phx_click: "delete", phx_value_id: question.id, data: [confirm: "Are you sure?"] %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>